'   UCF COP3330 Summer 2021 Assignment 5 Solution
'   Copyright 2021 rielly donnell

@startuml
'https://plantuml.com/class-diagram

App -- AppModel
AppModel -- AppController
AppModel -- Inventory
Inventory -- Item

class App {
    root: Parent
    scene: Scene

    main()
    start()
}

class AppController {
    appModel: AppModel

    tableView: TableView
    colName: TableColumn<Item, SimpleStringProperty>
    colSerialNumber: TableColumn<Item, SimpleStringProperty>
    colValue: TableColumn<Item, SimpleDoubleProperty>

    inventoryView: ObservableList

    txtSearch: TextField
    txtNewItemName: TextField
    txtNewItemSerialNumber: TextField
    txtNewItemValue: TextField

    validateName()
    validateSerialNumber()
    validateValue()

}

class AppModel {
    inventory: Inventory

    getInventory()
    setInventory()

    getTSV()
    getHTML()
    getJSON()
}

class Inventory {
    items: Set

    getItems()
    setItems()

    addItem()
    removeItem()
}

class Item {
    name: SimpleStringProperty
    serialNumber: SimpleStringProperty
    value: SimpleDoubleProperty

    getName()
    getSerialNumber()
    getValue()

    setName()
    setSerialNumber()
    setValue()
}

@enduml